flags: {}
packages:
- '.'
- location:
    git: git@github.com:plredmond/GPipe-GLFW.git
    commit: 6c86ee7def830ed211a3ea170598bcca555dcf66
  subdirs: [ GPipe-GLFW ]
  extra-dep: true
#- '../../gpipe-glfw/GPipe-GLFW'
- location:
    git: git@github.com:plredmond/GPipe-Core.git
    commit: bfa8035117b26809a0d542c2f45b94de8f2f5a47
  subdirs: [ GPipe-Core ]
  extra-dep: true
#- '../../@gpipe/GPipe-Core'
extra-deps: []
resolver: nightly-2016-12-03
nix:
    enable: false
    # Required C libraries: GL, X11, Xi, Xrandr, Xxf86vm, Xcursor, Xinerama
    packages:
        - mesa # GL for Intel graphics; something else for, eg. nvidia
        - xorg.libX11
        - xorg.libXi
        - xorg.libXrandr
        - xorg.libXxf86vm
        - xorg.libXcursor
        - xorg.libXinerama # there are other options
