flags: {}
packages:
- '.'
- location: #'../../gpipe-glfw'
    git: git@github.com:plredmond/GPipe-GLFW.git
    commit: 83c426bc2313e87c7d293f891757247dd52caf1c
  subdirs: [ GPipe-GLFW ]
  extra-dep: true
- location: #'../../@gpipe'
    git: git@github.com:tobbebex/GPipe-Core.git
    commit: 64284984489f7be1408fd11f1d8cc7881a1a14e9
  subdirs: [ GPipe-Core ]
  extra-dep: true
extra-deps: []
resolver: nightly-2017-04-23
nix:
    enable: false
    # Required C libraries: GL, X11, Xi, Xrandr, Xxf86vm, Xcursor, Xinerama
    packages:
        - mesa # GL for Intel graphics; something else for, eg. nvidia
        - xorg.libX11
        - xorg.libXi
        - xorg.libXrandr
        - xorg.libXxf86vm
        - xorg.libXcursor
        - xorg.libXinerama # there are other options
