flags: {}
packages:
- '.'
extra-deps: []
resolver: lts-7.8
nix:
    enable: true
    # Required C libraries: GL, X11, Xi, Xrandr, Xxf86vm, Xcursor, Xinerama
    packages:
        - mesa # GL for Intel graphics; something else for, eg. nvidia
        - xorg.libX11
        - xorg.libXi
        - xorg.libXrandr
        - xorg.libXxf86vm
        - xorg.libXcursor
        - xorg.libXinerama # there are other options
