flags: {}
packages:
- '.'
extra-deps:
- GPipe-2.2
- GPipe-GLFW-1.4.0
resolver: nightly-2017-04-23
nix:
    enable: false
    # Required C libraries: GL, X11, Xi, Xrandr, Xxf86vm, Xcursor, Xinerama
    packages:
        - mesa # GL for Intel graphics; something else for, eg. nvidia
        - xorg.libX11
        - xorg.libXi
        - xorg.libXrandr
        - xorg.libXxf86vm
        - xorg.libXcursor
        - xorg.libXinerama # there are other options
